<a href="https://colab.research.google.com/github/laerdon/llama-model-analysis/blob/main/llama_visualization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!huggingface-cli login


    _|    _|  _|    _|    _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|_|_|_|    _|_|      _|_|_|  _|_|_|_|
    _|    _|  _|    _|  _|        _|          _|    _|_|    _|  _|            _|        _|    _|  _|        _|
    _|_|_|_|  _|    _|  _|  _|_|  _|  _|_|    _|    _|  _|  _|  _|  _|_|      _|_|_|    _|_|_|_|  _|        _|_|_|
    _|    _|  _|    _|  _|    _|  _|    _|    _|    _|    _|_|  _|    _|      _|        _|    _|  _|        _|
    _|    _|    _|_|      _|_|_|    _|_|_|  _|_|_|  _|      _|    _|_|_|      _|        _|    _|    _|_|_|  _|_|_|_|

    To login, `huggingface_hub` requires a token generated from https://huggingface.co/settings/tokens .
Enter your token (input will not be visible): 
Add token as git credential? (Y/n) n
Token is valid (permission: write).
Your token has been saved to /root/.cache/huggingface/token
Login successful


In [2]:
! pip install --upgrade transformers
! pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.7/43.7 kB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 121.7 MB/s eta 0:00:00
  Attempting uninstall: transformers
    Found existing installation: transformers 4.42.4
    Uninstalling transformers-4.42.4:
      Successfully uninstalled transformers-4.42.4
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.3/527.3 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.9/39.9 MB 58.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 12.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 18.6 MB/s eta 0:00:00
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 14.0.2
    Uninstalling pyarrow-14.0.2:
      Successfully uninstalled pyarrow-14.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are instal

In [6]:
! pip install -U bitsandbytes

In [ ]:
# # prompt: mount drive

# from google.colab import drive
# drive.mount('/content/drive')

In [1]:
# # install LLaMA 2
# # Load model directly
# from transformers import AutoTokenizer, AutoModelForCausalLM

# tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf")
# model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-2-7b-hf")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [1]:
# install CUSTOM LLaMA 2
from datasets import load_dataset
from transformers import AutoTokenizer
from drive.MyDrive.llama_analysis.modeling_llama import LlamaForCausalLM

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf", trust_remote_token=True, token="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")
model = LlamaForCausalLM.from_pretrained("meta-llama/Llama-2-7b-hf", load_in_8bit=True)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
`low_cpu_mem_usage` was None, now set to True since model is quantized.


Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [2]:
from drive.MyDrive.llama_analysis.modeling_llama import identify_outliers
from drive.MyDrive.llama_analysis.modeling_llama import simple_identify_outliers
import tensorflow as tf
import torch

In [3]:
# model = model.to('cuda')
# # shouldn't i be able to put my LLaMA model onto the GPU with 22 GB?

In [4]:
#model.save_pretrained("meta-llama/Meta-Llama-3.1-8B")
#tokenizer.save_pretrained("meta-llama/Meta-Llama-3.1-8B")

# for some reason, Llama 3.1 is not working with the custom LlamaForCausalLM.

## setting up hooks for outlier suppression

In [5]:
# testing out torch.mean cause i'm a brick
# so i want everything in hooks to be (1, 4096) basically

x = torch.rand(1, 3, 10)
print(x)
y = torch.rand(1, 3, 10)
print(y)

print(torch.mean(x, 1))
print("\n========")

stack = torch.stack((x,y))

print(stack)

avged_stack = torch.mean(stack, 2)

print(avged_stack)

print(torch.mean(avged_stack, 0, True))

# print(torch.mean(torch.stack([x,y]), 1))

# i have to be averaging across the dimension of token_length(? if you know what i'm trying to get at) because

tensor([[[4.1271e-01, 2.6455e-01, 9.4175e-01, 4.3693e-01, 5.2515e-02,
          6.4193e-01, 2.1367e-01, 6.0808e-01, 7.4872e-01, 2.4860e-01],
         [3.0538e-01, 4.5339e-01, 1.2067e-01, 2.8558e-01, 8.8896e-01,
          9.1066e-01, 3.8242e-04, 5.9395e-01, 5.2917e-01, 6.2281e-01],
         [6.8579e-01, 2.0220e-01, 3.6733e-01, 9.3087e-01, 2.1996e-01,
          6.6939e-01, 9.8421e-01, 2.5884e-01, 6.4112e-02, 5.4037e-01]]])
tensor([[[0.2824, 0.7217, 0.4506, 0.0372, 0.4099, 0.1212, 0.8269, 0.2789,
          0.1141, 0.3892],
         [0.2447, 0.4873, 0.7463, 0.9658, 0.8628, 0.1815, 0.4764, 0.5165,
          0.7859, 0.3579],
         [0.4562, 0.0695, 0.5660, 0.7103, 0.4120, 0.6473, 0.0194, 0.9444,
          0.9940, 0.2728]]])
tensor([[0.4680, 0.3067, 0.4766, 0.5511, 0.3871, 0.7407, 0.3994, 0.4870, 0.4473,
         0.4706]])

tensor([[[[4.1271e-01, 2.6455e-01, 9.4175e-01, 4.3693e-01, 5.2515e-02,
           6.4193e-01, 2.1367e-01, 6.0808e-01, 7.4872e-01, 2.4860e-01],
          [3.0538e-01, 4.5

In [6]:
from collections import OrderedDict
from typing import Dict, Callable
import torch

def remove_all_hooks(model: torch.nn.Module) -> None:
    for name, child in model._modules.items():
        if child is not None:
            if hasattr(child, "_forward_hooks"):
                child._forward_hooks: Dict[int, Callable] = OrderedDict()
            elif hasattr(child, "_forward_pre_hooks"):
                child._forward_pre_hooks: Dict[int, Callable] = OrderedDict()
            elif hasattr(child, "_backward_hooks"):
                child._backward_hooks: Dict[int, Callable] = OrderedDict()
            remove_all_hooks(child)

In [7]:
remove_all_hooks(model)

In [8]:
# note: i think i also wrote this wrong again because i should probably have a
#   separate averaged stack for the token_len, [1, 4096], so that i can see at
#   each layer what is going on. ykwim? not just one 1D tensor the entire time
#   lol

# !!!!!!
# the hook was causing the problem? changing the output somehow?

class Hook():
  def __init__(self):
    self.output = None

  def __call__(self, module, input, output):
    # torch.mean instead of dumping everything into an output list. that's taking up way too much GPU RAM
    processed_output = torch.mean(output.detach(), 1)

    if self.output == None:
        self.output = processed_output
        print(f"FIRST OUTPUT: {self.output}, {self.output.shape}")
    else:
        # this naming is messed up. need to fix, because the avged stack only happens once we get to the self.output.
        # i think by doing the torch.mean, i'm essentially squeezing something
        stack = torch.cat((self.output, processed_output), dim=0)
        # print(f'stack: {stack}')
        # avged_stack = torch.mean(stack, 1)
        # print(f'avged_stack: {avged_stack}')
        self.output = torch.mean(stack, 0, True)
        # print(f"NOW WE OUTPUT: {self.output}")
    # return output

  def clear(self):
    self.output = None

In [9]:
# class PreHook():
#   def __init__(self):
#     self.output = []

#   def __call__(self, module, input):
#     self.output.append(input)
#     return input

#   def clear(self):
#     self.output = []

In [10]:
hook = Hook()

In [11]:
for n, m in model.named_modules():
  if "q_proj" in n:
    # m.register_forward_pre_hook(prehook)
    m.register_forward_hook(hook)

In [12]:
hook.clear()

In [13]:
model.forward(input_ids=tokenizer("Hello, my name is Jenny. I have a husband of four years, and ", return_tensors="pt").input_ids)
# wow this makes it a lot easier to see how this whole process of seq -> tokenizer -> ids -> forward should go lol

# IGNORE THESE OUTPUTS

print("done")

FIRST OUTPUT: tensor([[ 0.1405, -0.6890,  1.3770,  ..., -0.0880,  0.1879,  0.0111]],
       device='cuda:0', dtype=torch.float16), torch.Size([1, 4096])
done


## mk ii: evaluating perplexity

simpler this time, because i gave up on trying to use the lambada dataset and making my own custom functions for all this and just decided to use dataloader

In [14]:
from torch.utils.data import DataLoader
from datasets import load_dataset
import torch

dataset = load_dataset("wikitext", "wikitext-2-raw-v1", split="test[:5%]")

tokenizer.pad_token = tokenizer.eos_token

def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=512, return_tensors="pt")

tokenized_dataset = dataset.map(tokenize_function, batched=True, remove_columns=["text"])

tokenized_dataset = tokenized_dataset.with_format("torch")

# Create DataLoader
dataloader = DataLoader(tokenized_dataset, shuffle=False, batch_size=16)

In [15]:
# # Inspect a batch
# for batch in dataloader:
#     print(batch['input_ids'].shape)
#     print(batch['attention_mask'].shape)

In [16]:
# Evaluation loop
model.eval()
total_loss = 0
total_tokens = 0

with torch.no_grad():
    for batch in dataloader:
        print(batch["input_ids"])
        inputs = batch["input_ids"].clone().detach().to('cuda')
        # print(inputs.shape)
        # print(inputs) # one concern i have is that a lot of these samples look... exactly the same? which is weird? why
        attention_mask = batch["attention_mask"].clone().detach().to('cuda')

        outputs = model(inputs, attention_mask=attention_mask, labels=inputs)
        loss = outputs.loss

        total_loss += loss.item() * inputs.size(1)
        total_tokens += inputs.size(0) * inputs.size(1)

        torch.cuda.empty_cache()
        print("batch done")

# Calculate average loss and perplexity
avg_loss = total_loss / total_tokens
perplexity = torch.exp(torch.tensor(avg_loss))

print(f"Average Loss: {avg_loss:.4f}")
print(f"Perplexity: {perplexity:.4f}")

tensor([[    1,     2,     2,  ...,     2,     2,     2],
        [    1, 29871,   353,  ...,     2,     2,     2],
        [    1,     2,     2,  ...,     2,     2,     2],
        ...,
        [    1,     2,     2,  ...,     2,     2,     2],
        [    1, 29871,   353,  ...,     2,     2,     2],
        [    1,     2,     2,  ...,     2,     2,     2]])
batch done
tensor([[    1, 29871,   512,  ...,     2,     2,     2],
        [    1, 29871,   350,  ...,     2,     2,     2],
        [    1,     2,     2,  ...,     2,     2,     2],
        ...,
        [    1,     2,     2,  ...,     2,     2,     2],
        [    1,     2,     2,  ...,     2,     2,     2],
        [    1,     2,     2,  ...,     2,     2,     2]])
batch done
tensor([[    1, 29871,   353,  ...,     2,     2,     2],
        [    1,     2,     2,  ...,     2,     2,     2],
        [    1, 29871,  5334,  ...,     2,     2,     2],
        ...,
        [    1, 29871,   450,  ...,     2,     2,     2],
        [

## relic from old era, was trying to figure out the outlier suppression and failing

In [17]:
len(hook.output)

1

In [18]:
# so i can confirm that the MaskedLinear is being loaded

print(model)

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(32000, 4096)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (q_proj): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear8bitLt(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear8bitLt(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear8bitLt(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear8bitLt(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm

In [19]:
hook.output[0]

tensor([ 0.1362,  0.0721, -0.0400,  ..., -0.2096, -0.0903,  0.4907],
       device='cuda:0', dtype=torch.float16)

In [20]:
# for n, m in model.named_modules():
#   if "q_proj" in n:
#     print(m.weight)

# weights are irrelevant i'm looking for activations

In [21]:
len(hook.output)

1

In [22]:
# hook.output[0][0] is the first module's activation matrix. for some reason the tensor hook.output[0] is 3D, with the first dimension being size 1, so you just have to unwrap ig

test_identify_outliers = hook.output[30]

IndexError: index 30 is out of bounds for dimension 0 with size 1

In [ ]:
test_identify_outliers.shape

In [ ]:
test_identify_outliers = test_identify_outliers.squeeze()

In [ ]:
test_identify_outliers

In [ ]:
# checking that identify_outliers works properly

# wait but this seems to show that it works?
# how come when i bring
# print(tf.reduce_sum(tf.cast(identify_outliers(test_identify_outliers, threshold=2.0), tf.float32)))
# print(tf.reduce_sum(tf.cast(simple_identify_outliers(test_identify_outliers, threshold=2), tf.float32)))

# tens = torch.eye(3) * 3
# print(tf.reduce_sum(tf.cast(identify_outliers(tens, threshold=1), tf.float32)))

## some nice little graphing thingies

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# !!!!
# need to fix
def create_heatmap(activations, input_text):
    # Process activations
    activation_matrix = activations.detach().numpy()
    print(activation_matrix)
    # Create heatmap
    plt.figure(figsize=(12, 8))
    sns.heatmap(activation_matrix, cmap="viridis", cbar_kws={'label': 'Activation Strength'})
    plt.title(f"LLaMA Layer Activations for: '{input_text}'")
    plt.xlabel("Neuron Index")
    plt.ylabel("Token")
    plt.tight_layout()
    plt.show()

def create_scatterplot(activations, input_text):
    # Process activations
    activation_matrix = activations.detach().numpy()
    plt

In [ ]:
# for i in range(len(hook.output)):
#   create_heatmap(hook.output[i][0], "Hello, my name is Jenny. I have a husband of four years, and ")

In [ ]:
import torch
# find index of maximum neuron activation for each layer


# 30 vs 62
module = 24
token = 2

selected_layer = hook.output[0]

print(selected_layer)
max_i = torch.argmax(selected_layer)
max = torch.max(selected_layer)
print(max_i)
print(max)

In [ ]:
input_text = "Hello, my name is Jenny. I have a husband of four years, and "

plt.figure()
plt.plot(selected_layer.detach().cpu().numpy())
plt.title(f"LLaMA Layer Activations for: '{input_text}'")
plt.xlabel("Neuron Index")
plt.ylabel("Token")
plt.show()

## trying to evaluate perplexity with lambada. result: perplexity 30000

In [ ]:
import torch.nn.functional as F
from torch.nn.functional import pad
from datasets import load_dataset

In [ ]:
dataset = load_dataset('lambada', split='validation[:1%]')

In [ ]:
# write an evaluator class that will use perplexity

class Evaluator:
    def __init__(self, dataset, tokenizer):
        self.dataset = dataset
        self.tokenizer = tokenizer

        # tokenize the dataset
        def tokenize_function(examples):
            example = self.tokenizer(examples['text'])
            return example

        self.dataset = self.dataset.map(tokenize_function, batched=True)
        self.dataset.set_format(type='torch', columns=['input_ids'])

    @torch.no_grad()
    def inference(self, model, batch_size=16):

        model.eval()
        # The task is to predict the last word of the input.
        # total, hit = 0, 0

        print("Length of dataset:", len(self.dataset))  # Check dataset length

        logits_and_labels = {
            'logits': [],
            'labels': []
        }

        for i in range(0, len(self.dataset), batch_size):
            batch = self.dataset[i:i+batch_size]
            # batch['input_ids'] is a list of tensors

            ls_of_input_ids = batch['input_ids']

            ls_of_labels = []
            truncated_ls_of_input_ids = []

            for input_ids in ls_of_input_ids:
                ls_of_labels.append(input_ids[-1])
                truncated_ls_of_input_ids.append(input_ids[:-1])

            tens_2D_padded_input_ids = torch.nn.utils.rnn.pad_sequence(truncated_ls_of_input_ids, batch_first=True, padding_value=2)
            labels = torch.stack(ls_of_labels).unsqueeze(1)

            print(tens_2D_padded_input_ids.shape)
            print(labels.shape)

            # torch.stack() works for turning lists into tensors and putting tensors together type shi

            ### THIS SHOULD WORK?

            with torch.no_grad():
                outputs = model(tens_2D_padded_input_ids) # ok maybe i don't even need to pass in the labels at all
                # print("Shape of model outputs logits:", outputs.logits.shape) # Check shape of model outputs
                # print("Shape of model outputs labels:", labels.shape) # Check shape of model outputs
                logits_and_labels['logits'].append(outputs.logits)
                logits_and_labels['labels'].append(labels)
                print(len(logits_and_labels['logits']))
                print(len(logits_and_labels['labels']))
                # outputs.logits.shape is [batch_len, seq_len, vocab_size]. the vocab_size dimension is going to contain the pre-softmax probabilities of the next token.

        return logits_and_labels

            # i'm going to handle calculating loss, perplexity, the whole shebang in another function



##################
# all this is shit

        # for item in batch:
        #     print(type(item))
            #print(item['input_ids'].shape)

        #     arr_of_input_ids = torch.stack([item['input_ids'] for item in batch]).cuda()
        #     input_ids = batch['input_ids'].cuda().unsqueeze(0)
        #     # print("Shape of input_ids before padding:", input_ids.shape)  # Add this line
        #     label = input_ids[:, -1]
        #     pad_len = 512 - input_ids.shape[1]
        #     input_ids = pad(input_ids, (0, pad_len), value=1)

        #     torch.cuda.empty_cache()

        #     outputs = model(input_ids)
        #     last_token_logits = outputs.logits[:, -2-(pad_len), :]
        #     pred = last_token_logits.argmax(dim=-1)
        #     total += label.size(0)
        #     hit += (pred == label).sum().item()

        # acc = hit / total

In [ ]:
# import gc
# gc.collect()

In [ ]:
# model = model.to('cuda')

In [ ]:
evaluator = Evaluator(dataset, tokenizer)

In [ ]:
# no one cares anymore

# if tokenizer.pad_token_id is not None:
#     pad_token_id = tokenizer.pad_token_id
#     print(f"Padding token ID: {pad_token_id}")
# else:
#     print("No specific padding token set.")

In [ ]:
logits_and_labels = evaluator.inference(model)

# why didn't it go all the way lmfao
# i'm dumb i indented the return too far in lmfao
# again, another dumb mistake—logits and labels was in the for loop

In [ ]:
labels = logits_and_labels['labels']
logits = logits_and_labels['logits']

In [ ]:
print(logits[0].shape)
print(labels[0].shape)

In [ ]:
squeezed_labels = [label.squeeze(1) for label in labels]

In [ ]:
last_token_logits = [tens[:, -1, :] for tens in logits]

## confused as to why my perplexity is 33000

trying to fix that

In [ ]:
print(last_token_logits[0].shape)

In [ ]:
print(last_token_logits[0][1])

In [ ]:
print(labels[0][1])

In [ ]:
print(last_token_logits[0][1][273])

In [ ]:
plt.figure()
plt.plot(last_token_logits[0][1].detach().numpy())
plt.title(f"LLaMA Layer Activations")
plt.xlabel("Sample")
plt.ylabel("Logit Activation")
plt.show()

In [ ]:
# i'm not sure why this weird behavior is occurring i'm going to see what loss i get with a different strategy

## loss + perplexity functions

In [ ]:
"""
calculates loss
batch_last_token_logits: [batch_size, vocab_size]
squeezed_batch_labels: [batch_size]

"""
def calculate_loss(batch_last_token_logits, squeezed_batch_labels):
    return F.cross_entropy(input=batch_last_token_logits, target=squeezed_batch_labels)

In [ ]:
loss = calculate_loss(last_token_logits[0], squeezed_labels[0])

In [ ]:
torch.exp(loss)

In [ ]:
# more manual, crappier version. do not like it. however, it does give the same result.

# def calculate_perplexity(batch_logits, batch_labels):
#     last_token_logits = batch_logits[:, -1, :]
#     probabilities = F.softmax(last_token_logits, dim=-1)
#     label_probabilities = torch.gather(input=probabilities, dim=1, index=batch_labels)  # Shape: (batch_size, 1)
#     print(label_probabilities)
#     nll = -torch.log(label_probabilities)  # Shape: (batch_size, 1)
#     mean_nll = nll.mean().item()
#     perplexity = torch.exp(torch.tensor(mean_nll)).item()
#     return perplexity

In [ ]:
print(calculate_perplexity(logits[0], labels[0]))

# somehow the non-suppressed model is more perplexed lol

In [ ]:
# # DO NOT DO THIS IT BREAKS THE THING

# # reset GPU ram

# !pip install numba
# from numba import cuda
# device = cuda.get_current_device()
# device.reset()

In [ ]:
import gc
gc.collect()

In [ ]:
# torch.cuda.max_memory_allocated()

In [ ]:
# torch.cuda.memory_allocated()

In [ ]:
# !nvidia-smi

In [ ]:
# error : RuntimeError: CUDA error: invalid argument
# CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
# For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
# Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

# According to https://discuss.pytorch.org/t/torch-prod-produces-runtimeerror-cuda-driver-error-invalid-argument/179054/17:

# The cluster admins have found the solution, which was to clean .cache/torch/kernels which contained a bunch of files like the following:

# reduction_prod_arch7.0_nvrtc11.2_sass_29385_edd9f40fe47533f6cc3bc6072826690d02ec24ef

# It looks like cleaning it removed the problem altogether.